apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: external-dns-identity
spec:
  type: 0
  ResourceID: ${ResourceID}
  ClientID: ${ClientID}

---

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: external-dns-identity-binding
spec:
  AzureIdentity: external-dns-identity
  Selector: $IDENTITY_NAME