# Please see https://github.com/Azure/aad-pod-identity for more information
# https://github.com/kubernetes-sigs/external-dns/issues/1456
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: external-dns
spec:
  type: 0
  ResourceID: ${ResourceID}
  ClientID: ${ClientID}

---

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: external-dns
spec:
  AzureIdentity: external-dns
  Selector: external-dns